package com.lmscrm.backend.controller.admin;

import com.lmscrm.backend.domain.entity.User;
import com.lmscrm.backend.service.DashboardService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/v1/admin/reports")
@RequiredArgsConstructor
@Tag(name = "Admin Report Controller", description = "Endpoints for generating organizational reports")
public class AdminReportController {

    private final DashboardService dashboardService;

    @GetMapping("/generate")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(summary = "Generate organization report (PDF/Excel)")
    public ResponseEntity<byte[]> generateReport(@AuthenticationPrincipal User currentUser) {
        // Simulating PDF generation
        String content = "LMSHub Organization Report\n" +
                "Organization ID: " + currentUser.getOrganizationId() + "\n" +
                "Generated by: " + currentUser.getFullName() + "\n" +
                "This is a simulated report for Organization " + currentUser.getOrganizationId();
        
        byte[] pdfBytes = content.getBytes();

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=report.pdf")
                .contentType(MediaType.APPLICATION_PDF)
                .body(pdfBytes);
    }
}
