import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "1.5rem",
        lg: "2rem",
      },
      screens: {
        "2xl": "1400px",
      },
    },
    screens: {
      xs: "420px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      maxWidth: {
        "7xl": "1600px", // Expand the default 7xl layout for a wider dashboard site-wide
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary-hsl))",
          foreground: "hsl(var(--primary-foreground))",
          light: "var(--primary-light)",
          dark: "var(--primary-dark)",
          glow: "var(--primary-glow)",
          border: "var(--primary-border)",
          muted: "var(--primary-muted)",
        },
        purple: {
          50: "hsl(var(--primary-hsl) / 0.05)",
          100: "hsl(var(--primary-hsl) / 0.1)",
          200: "hsl(var(--primary-hsl) / 0.2)",
          300: "hsl(var(--primary-hsl) / 0.3)",
          400: "hsl(var(--primary-hsl) / 0.4)",
          500: "hsl(var(--primary-hsl))",
          600: "var(--primary-dark)",
          700: "var(--primary-dark)",
          800: "var(--primary-dark)",
          900: "var(--primary-dark)",
          950: "var(--primary-dark)",
          DEFAULT: "hsl(var(--primary-hsl))",
        },
        violet: {
          50: "hsl(var(--primary-hsl) / 0.05)",
          100: "hsl(var(--primary-hsl) / 0.1)",
          200: "hsl(var(--primary-hsl) / 0.2)",
          300: "hsl(var(--primary-hsl) / 0.3)",
          400: "hsl(var(--primary-hsl) / 0.4)",
          500: "hsl(var(--primary-hsl))",
          600: "var(--primary-dark)",
          700: "var(--primary-dark)",
          800: "var(--primary-dark)",
          900: "var(--primary-dark)",
          950: "var(--primary-dark)",
          DEFAULT: "hsl(var(--primary-hsl))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--primary-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--primary-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        role: {
          superadmin: "hsl(var(--role-superadmin))",
          admin: "hsl(var(--role-admin))",
          payment: "hsl(var(--role-payment))",
          teacher: "hsl(var(--role-teacher))",
          student: "hsl(var(--role-student))",
          moderator: "hsl(var(--role-moderator))",
          support: "hsl(var(--role-support))",
          content: "hsl(var(--role-content))",
        }
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        display: ['"Manrope"', 'system-ui', 'sans-serif'],
        sans: ['"Manrope"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(10px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { "0%": { opacity: "0", transform: "scale(0.95)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        "glow-pulse": { "0%, 100%": { opacity: "0.6" }, "50%": { opacity: "1" } },
        "float": { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-12px)" } },
        "shimmer": { "100%": { transform: "translateX(100%)" } },
        "wave": {
          "0%":   { transform: "rotate(0deg)" },
          "10%":  { transform: "rotate(18deg)" },
          "20%":  { transform: "rotate(-8deg)" },
          "30%":  { transform: "rotate(18deg)" },
          "40%":  { transform: "rotate(-4deg)" },
          "50%":  { transform: "rotate(12deg)" },
          "60%":  { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(0deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        "scale-in": "scale-in 0.3s ease-out",
        "glow-pulse": "glow-pulse 3s ease-in-out infinite",
        "float": "float 6s ease-in-out infinite",
        "shimmer": "shimmer 1.5s infinite linear",
        "wave": "wave 2s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
