package com.lmscrm.backend.service.exam.parser;

import com.lmscrm.backend.exception.UnsupportedFormatException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.springframework.stereotype.Component;

import java.nio.charset.StandardCharsets;
import java.util.List;

/**
 * ParserFactory — selects the correct parser based on HTML metadata.
 *
 * Detection order:
 *   1. <html data-format="lmshub-v1"> attribute
 *   2. <meta name="lmshub:format" content="lmshub-v1"> tag
 *   3. If neither found → throw UnsupportedFormatException
 *
 * NEVER detects by filename.
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class ParserFactory {

    private final List<ExamParser> parsers;

    /**
     * Returns the correct ExamParser based on the format version
     * declared inside the HTML content itself.
     */
    public ExamParser getParser(byte[] htmlBytes) {
        String formatVersion = extractFormatVersion(htmlBytes);
        log.info("Detected LMSHub HTML format version: {}", formatVersion);

        return parsers.stream()
                .filter(p -> p.supports(formatVersion))
                .findFirst()
                .orElseThrow(() -> new UnsupportedFormatException(
                        "HTML format '" + formatVersion + "' is not supported. " +
                        "Expected: <html data-format=\"lmshub-v1\"> or " +
                        "<meta name=\"lmshub:format\" content=\"lmshub-v1\">. " +
                        "Make sure the HTML was generated by the LMSHub Layout Converter."
                ));
    }

    /**
     * Extracts the format version string from HTML metadata.
     * Returns empty string if not found.
     */
    private String extractFormatVersion(byte[] htmlBytes) {
        try {
            String html = new String(htmlBytes, StandardCharsets.UTF_8);
            Document doc = Jsoup.parse(html);

            // 1. Try <html data-format="...">
            Element htmlEl = doc.selectFirst("html");
            if (htmlEl != null) {
                String format = htmlEl.attr("data-format");
                if (!format.isBlank()) return format.toLowerCase().trim();
            }

            // 2. Try <meta name="lmshub:format" content="...">
            Element metaEl = doc.selectFirst("meta[name=lmshub:format]");
            if (metaEl != null) {
                String content = metaEl.attr("content");
                if (!content.isBlank()) return content.toLowerCase().trim();
            }
        } catch (Exception e) {
            log.warn("Failed to extract format version from HTML", e);
        }
        return "";
    }
}
